name: finance_helper
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.6
  get_it: ^7.2.0
  go_router: ^6.0.1
  hooks_riverpod: ^2.3.3
  intl: ^0.18.1
  stacked_services: ^1.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
